let confdir=$HOME."/dotfiles/vim/"

source ~/dotfiles/editor_configs/general_editor_config.vim

" download and install vim-plug
let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" set the runtime path to include vim-plug and initialize
call plug#begin('~/.vim/bundle')

source ~/dotfiles/editor_configs/vim_plugins_list.vim

" Plugin list end
call plug#end()

source ~/dotfiles/editor_configs/vim_plugins_conf.vim

" ocaml stuff

if system("opam --version")
    let g:opamshare = substitute(system('opam config var share'),'\n$','','''') . "/merlin/vim"
    set rtp+=g:opamshare
    set rtp^="/home/connernilsen/.opam/5.0.0/share/ocp-indent/vim"
endif

" ## added by OPAM user-setup for vim / base ## 93ee63e278bdfc07d1139a748ed3fff2 ## you can edit, but keep this line
let s:opam_share_dir = system("opam config var share")
let s:opam_share_dir = substitute(s:opam_share_dir, '[\r\n]*$', '', '')

let s:opam_configuration = {}

function! OpamConfMerlin()
  let l:dir = s:opam_share_dir . "/merlin/vim"
  execute "set rtp+=" . l:dir
endfunction
let s:opam_configuration['merlin'] = function('OpamConfMerlin')

let s:opam_packages = ["merlin"] " \"ocp-indent\", \"ocp-index\"]
let s:opam_check_cmdline = ["opam list --installed --short --safe --color=never"] + s:opam_packages
let s:opam_available_tools = split(system(join(s:opam_check_cmdline)))
for tool in s:opam_packages
  " Respect package order (merlin should be after ocp-index)
  if count(s:opam_available_tools, tool) > 0
    call s:opam_configuration[tool]()
  endif
endfor
